baseUrl: "http://localhost:3000/tars/v1"
gatewayUrl: "http://localhost:3000/tars/v1/gateway"
controlNodeBaseUrl: "http://192.168.0.52:38080/tars/v1"
rosBaseUrl: "http://192.168.0.52:38081/ros_api/v1"
chatBaseUrl: "http://192.168.2.159:9999/api/v3"
frontendBaseUrl: "http://localhost:3000"
internetPingUrl: "https://tars.finetool.cn/ping"
username: "admin"
password: "admin"
phone: "15650526180"
sessionCookie: "session=b6952a37-38c7-425e-a4cc-1807677d7675"
